# Generated by Django 4.0.5 on 2022-07-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zerodha_token',
        ),
    ]
