# Generated by Django 4.0.5 on 2022-07-01 06:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_zerodha_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerodhadata',
            name='access_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='api_key',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='broker',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='enctoken',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='exchanges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='order_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='public_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='refresh_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='user_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='user_shortname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='user_type',
            field=models.CharField(blank=True, default='individual', max_length=50, null=True),
        ),
    ]
