# Generated by Django 4.0.5 on 2022-07-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_zerodhadata_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerodhadata',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
    ]
