# Generated by Django 4.0.5 on 2022-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_zerodhadata_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodhadata',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
