# Generated by Django 4.0.5 on 2022-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_zerodhadata_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.TextField(default=''),
        ),
    ]
