# Generated by Django 4.0.5 on 2022-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
