# Generated by Django 4.0.5 on 2022-07-17 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_pan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.TextField()),
                ('exchange_token', models.TextField()),
                ('tradingsymbol', models.TextField()),
                ('name', models.TextField()),
                ('last_price', models.FloatField()),
                ('expiry', models.DateField()),
                ('strike', models.FloatField()),
                ('tick_size', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(default='', max_length=4)),
                ('segment', models.TextField()),
                ('exchange', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZerodhaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_symbol', models.CharField(default='', max_length=20)),
                ('exchange', models.CharField(default='', max_length=10)),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=5, null=True)),
                ('order_type', models.CharField(default='', max_length=20)),
                ('quantity', models.IntegerField()),
                ('product', models.TextField()),
                ('price', models.FloatField()),
                ('trigger_price', models.FloatField()),
                ('disclosed_quantity', models.IntegerField()),
                ('validity', models.CharField(choices=[('DAY', 'DAY'), ('IOC', 'IOC'), ('TTL', 'TTL')], max_length=5)),
                ('validity_ttl', models.IntegerField()),
                ('iceberg_legs', models.IntegerField()),
                ('iceberg_quantity', models.FloatField()),
                ('tag', models.TextField(default='')),
                ('order_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSusbcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_id', models.TextField()),
                ('payment_gateway', models.TextField()),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.usersusbcription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_symbol', models.CharField(default='', max_length=20)),
                ('exchange', models.CharField(default='', max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=5, null=True)),
                ('if_not_invest_then_what', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('zerodha_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to='core.zerodhatransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
