# Generated by Django 4.0.5 on 2022-07-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_marketquote_zerodhatransaction_usersusbcription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSusbcription',
            new_name='UserSubscription',
        ),
    ]
