# Generated by Django 4.0.5 on 2022-07-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_tradingsymbol_marketquote_trading_symbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketquote',
            old_name='last_price',
            new_name='price',
        ),
    ]
