# Generated by Django 4.0.5 on 2022-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_last_price_marketquote_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketquote',
            name='change',
            field=models.FloatField(null=True),
        ),
    ]
