# Generated by Django 4.0.5 on 2022-07-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_marketquote_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketquote',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
