# Generated by Django 4.0.5 on 2022-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_marketquote_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketquote',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='zerodhadata',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
