# Generated by Django 4.0.5 on 2022-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='index_listing',
            field=models.TextField(default='', null=''),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='series',
            field=models.TextField(default='', null=''),
        ),
    ]
