# Generated by Django 4.0.5 on 2022-07-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_stocks_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketquote',
            name='data_from',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='exchange_token',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='strike',
        ),
        migrations.RemoveField(
            model_name='marketquote',
            name='tick_size',
        ),
    ]
