# Generated by Django 4.0.5 on 2022-07-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_marketquote_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.TextField(default='', unique=True),
        ),
    ]
