# Generated by Django 4.0.5 on 2022-07-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_user_firebase_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='zerodha_transaction',
        ),
        migrations.DeleteModel(
            name='ZerodhaTransaction',
        ),
    ]
