# Generated by Django 4.0.5 on 2022-07-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_transaction_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodhadata',
            name='funds',
            field=models.FloatField(default=0),
        ),
    ]
