# Generated by Django 4.0.5 on 2022-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_investmentinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
