# Generated by Django 4.0.5 on 2022-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_transaction_if_not_invest_then_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='if_not_invest_then_what',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
