# Generated by Django 4.0.5 on 2022-08-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_transaction_if_not_invest_then_what'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='show_after_trade_modal',
            field=models.BooleanField(default=True),
        ),
    ]
