# Generated by Django 4.0.5 on 2022-08-20 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zerodhadata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='zerodhadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
