# Generated by Django 4.0.5 on 2022-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_zerodhadata_options_zerodhadata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerodhadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
