# Generated by Django 4.0.5 on 2022-07-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='uuid',
            new_name='uid',
        ),
    ]
