# Generated by Django 4.0.5 on 2022-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_adminnotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_USER', 'NEW_USER'), ('SUBSCRIPTION', 'SUBSCRIPTION'), ('TRADE', 'TRADE')], max_length=13, null=True),
        ),
    ]
