# Generated by Django 4.0.5 on 2022-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_contactdata_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
