# Generated by Django 4.1.3 on 2022-12-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_user_firebase_token"),
        ("wallets", "0002_alter_wallet_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="userprofile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_wallet",
                to="core.userprofile",
            ),
        ),
    ]
