# Generated by Django 4.1.3 on 2022-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_prize_prize_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizfile",
            name="file_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
