# Generated by Django 4.1.3 on 2022-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_quizfile_file_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="end_date_time",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="start_date_time",
        ),
        migrations.AddField(
            model_name="quiz",
            name="end_date",
            field=models.DateField(default="2022-12-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="end_time",
            field=models.TimeField(default="12:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="start_date",
            field=models.DateField(default="2044-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="start_time",
            field=models.TimeField(default="12:00"),
            preserve_default=False,
        ),
    ]
