# Generated by Django 4.1.3 on 2022-11-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_remove_quiz_end_date_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuizFile",
            new_name="QuestionFile",
        ),
    ]
