# Generated by Django 4.1.3 on 2022-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_rename_quizfile_questionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("ACTIVE", "Active"),
                    ("AWAITING_RESULTS", "Awaiting Results"),
                    ("COMPLETED", "Completed"),
                ],
                default="UPCOMING",
                max_length=50,
            ),
        ),
    ]
