# Generated by Django 4.1.3 on 2022-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_quiz_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="first_prize_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz",
            name="first_prize_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="second_prize_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz",
            name="second_prize_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="third_prize_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz",
            name="third_prize_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("ACTIVE", "Active"),
                    ("AWAITING_RESULTS", "Awaiting Results"),
                    ("COMPLETED", "Completed"),
                ],
                default="UPCOMING",
                max_length=50,
            ),
        ),
    ]
