# Generated by Django 4.1.3 on 2022-11-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0007_quiz_first_prize_image_quiz_first_prize_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="first_prize_image",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="first_prize_name",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="second_prize_image",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="second_prize_name",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="third_prize_image",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="third_prize_name",
        ),
    ]
