# Generated by Django 4.1.3 on 2022-11-25 17:26

from django.db import migrations, models
import quizzes.utils


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_remove_quiz_first_prize_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prize",
            old_name="quiz_id",
            new_name="quiz",
        ),
        migrations.RenameField(
            model_name="questionfile",
            old_name="quiz_id",
            new_name="quiz",
        ),
        migrations.AlterField(
            model_name="prize",
            name="image",
            field=models.FileField(upload_to=quizzes.utils.prize_images_dir),
        ),
        migrations.AlterField(
            model_name="questionfile",
            name="file",
            field=models.FileField(upload_to=quizzes.utils.question_files_upload_dir),
        ),
    ]
