# Generated by Django 4.1.3 on 2022-12-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_user_firebase_token"),
        ("quizzes", "0012_question_correct_choice_alter_question_question_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WinnerConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("second_name", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=5)),
                ("phone_number", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.TextField(max_length=500)),
                ("terms_consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consented_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
